# ========== Home Assistant Base Configuration ==========
default_config:

# Set timezone from environment (optional)
homeassistant:
  name: Home Assistant
  time_zone: America/Chicago

# Enable MQTT integration and point to Mosquitto container
#mqtt:
#  broker: mosquitto
#  port: 1883
#  discovery: true
#  discovery_prefix: homeassistant
